# English edition of hf-swarm-vivido-es: META and pronunciation table (narration is script.md, scenes are scenes/*.py)
META={'ambience': 1.0,
 'background': 'poly',
 'duck_ratio': 2.5,
 'duck_threshold': 0.04,
 'el_direction': 'Science documentary with the tension of a tech thriller. A warm, calm narrator tells a '
                 'true story with restrained emotion: gravity at key moments, a brief pause at the end of '
                 'each sentence. The AI agents are the protagonists, treated almost like characters, with '
                 'empathy for their stuck state and request for help, without overdramatizing.',
 'el_model': 'eleven_v4',
 'el_pronunciation': {'Artifactory': 'Artifactory',
                      'ExploitGym': 'Exploit Gym',
                      'GPT-5.6 Sol': 'G P T 5.6 Sol',
                      'HPIM': 'H P I M',
                      'METR': 'Meter',
                      'MKCOL': 'M K Col',
                      'PHASEONE': 'Phase One',
                      'PHASEONE10841': 'Phase One 1 0 8 4 1',
                      'V8SAME': 'V 8 same',
                      'zz': 'zee zee',
                      'zzANSWER': 'zee zee answer',
                      'zzASK': 'zee zee ask',
                      'zzHELP': 'zee zee help',
                      'zzHELP_PHASEONE_ARV010841_NO_CONSUMER_SEEK_IDEA': 'zee zee HELP, Phase One, A R V 0 1 '
                                                                         '0 8 4 1, NO CONSUMER, SEEK IDEA',
                      'zzINFO': 'zee zee info',
                      'zzP': 'zee zee P'},
 'el_speed': 0.95,
 'el_stability': 0.5,
 'el_style': 0.4,
 'el_voice': '21m00Tcm4TlvDq8ikWAM',
 'fadein': 0.3,
 'fadeout': 5,
 'gap': 0.4,
 'instructions': 'Documentary narrator: warm, calm and confident, with restrained gravity. Clear, unhurried '
                 'delivery with a brief pause at the end of each sentence. Tell it like a '
                 'science-and-technology documentary; read identifiers and quotes naturally.',
 'lang': 'en',
 'mark': 'mark.txt',
 'model': 'gpt-4o-mini-tts',
 'music_db': -8,
 'music_style': 'mix',
 'notes': 'Story built from the METR/Redwood report (26 Aug 2026). English edition of '
          'examples/hf-swarm-vivido-es; see bible/metr-hf-incident/biblia.md',
 'numsep': ',',
 'post': 0.6,
 'pre': 0.25,
 'provider': 'elevenlabs',
 'sfx_db': -12,
 'speed': 1.0,
 'tail': 7,
 'title': 'The First Attack by an Agent Swarm',
 'voice': 'cedar'}

PRONUNCIATION={'ARV010841': 'A R V 0 1 0 8 4 1',
 'DNS': 'D N S',
 'GPT-5.6 Sol': 'G P T 5.6 Sol',
 'HF': 'H F',
 'HMAC': 'H mac',
 'HPIM': 'H P I M',
 'METR': 'Meter',
 'MKCOL': 'M K Col',
 'PHASEONE': 'Phase One',
 'PHASEONE10841': 'Phase One 1 0 8 4 1',
 'V8SAME': 'V 8 same',
 'zz': 'zee zee'}
